services:
    sip3k-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sip3k_app
        restart: always
        expose:
            - "3000"
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - TZ=Asia/Jakarta
        volumes:
            - ./public:/app/public
            - ./data:/app/data
            - ./logs:/app/logs
    sip3k-cron:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sip3k_cron
        restart: always
        command: ["bun", "run", "dist/cron.js"]
        env_file:
            - .env
        environment:
            - NODE_ENV=production
            - TZ=Asia/Jakarta
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs
        depends_on:
            - sip3k-app
    sip3k-backup:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sip3k_backup
        restart: always
        command: ["bun", "run", "dist/backup.js"]
        environment:
            - NODE_ENV=production
            - TZ=Asia/Jakarta
        volumes:
            - ./data:/app/data
            - ./logs:/app/logs
        depends_on:
            - sip3k-app
    sip3k-nginx:
        image: nginx:alpine
        container_name: sip3k_nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - sip3k-app
